/*
  questions.js – Fragenpool "Glücksrad des Wissens – Klasse 2"

  Inhalt: 180 Fragen (60 Mathematik, 60 Deutsch, 60 Allgemeinwissen),
  übernommen aus dem Fragenpool-Dokument für Klasse 2.

  Jede Frage besitzt:
    id          eindeutige Kennung (M2-###, D2-###, AW2-###)
    category    "Mathematik" | "Deutsch" | "Allgemeinwissen"
    subcategory Bereich bzw. Unterkategorie aus dem Fragenpool
    type        "closed" | "open" | "fun"
    question    Fragetext
    answer      Lösung bzw. akzeptierte Lösung

  Allgemeinwissen enthält die fünf Unterkategorien Welt & Länder,
  Natur & Tiere, Alltag & Gesellschaft, Technik & Medien und Kultur
  mit je 12 Fragen. Die App zieht sie reihum (siehe app.js).
*/

const QUESTIONS = [
  /* -------------------------------------------------------------- */
  /* MATHEMATIK – 60 Fragen                                         */
  /* -------------------------------------------------------------- */
  { id: "M2-001", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 5 + 3?", answer: "8" },
  { id: "M2-002", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 10 - 4?", answer: "6" },
  { id: "M2-003", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Welche Zahl kommt direkt nach 12?", answer: "13" },
  { id: "M2-004", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Welche Zahl kommt direkt vor 9?", answer: "8" },
  { id: "M2-005", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 7 + 2?", answer: "9" },
  { id: "M2-006", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 14 - 3?", answer: "11" },
  { id: "M2-007", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "6 + wie viel = 10?", answer: "4" },
  { id: "M2-008", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist das Doppelte von 4?", answer: "8" },
  { id: "M2-009", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist die Hälfte von 10?", answer: "5" },
  { id: "M2-010", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Welche Zahl ist größer: 13 oder 9?", answer: "13" },
  { id: "M2-011", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 8 + 7?", answer: "15" },
  { id: "M2-012", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 16 - 8?", answer: "8" },
  { id: "M2-013", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 9 + 6?", answer: "15" },
  { id: "M2-014", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 18 - 7?", answer: "11" },
  { id: "M2-015", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 7 + 7?", answer: "14" },
  { id: "M2-016", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 15 - 9?", answer: "6" },
  { id: "M2-017", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 10 + 5?", answer: "15" },
  { id: "M2-018", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 20 - 6?", answer: "14" },
  { id: "M2-019", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 12 + 4?", answer: "16" },
  { id: "M2-020", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 19 - 9?", answer: "10" },
  { id: "M2-021", category: "Mathematik", subcategory: "Zahlbeziehungen", type: "closed", question: "Welche Zahl liegt zwischen 14 und 16?", answer: "15" },
  { id: "M2-022", category: "Mathematik", subcategory: "Muster & Strukturen", type: "closed", question: "Wie geht die Reihe weiter: 5, 7, 9, __?", answer: "11" },
  { id: "M2-023", category: "Mathematik", subcategory: "Muster & Strukturen", type: "closed", question: "Wie geht die Reihe weiter: 20, 18, 16, __?", answer: "14" },
  { id: "M2-024", category: "Mathematik", subcategory: "Muster & Strukturen", type: "closed", question: "Wie geht die Reihe weiter: 2, 4, 6, 8, __?", answer: "10" },
  { id: "M2-025", category: "Mathematik", subcategory: "Zahlbeziehungen", type: "closed", question: "11 = 5 + wie viel?", answer: "6" },
  { id: "M2-026", category: "Mathematik", subcategory: "Zahlbeziehungen", type: "closed", question: "Wie groß ist der Unterschied zwischen 17 und 12?", answer: "5" },
  { id: "M2-027", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 4 + 4 + 2?", answer: "10" },
  { id: "M2-028", category: "Mathematik", subcategory: "Zahlen & Operationen", type: "closed", question: "Wie viel ist 13 - 3 - 4?", answer: "6" },
  { id: "M2-029", category: "Mathematik", subcategory: "Sachrechnen", type: "closed", question: "Lena hat 7 Äpfel und bekommt 5 dazu. Wie viele hat sie jetzt?", answer: "12" },
  { id: "M2-030", category: "Mathematik", subcategory: "Sachrechnen", type: "closed", question: "Ben hat 15 Murmeln und gibt 4 ab. Wie viele bleiben?", answer: "11" },
  { id: "M2-031", category: "Mathematik", subcategory: "Sachrechnen", type: "closed", question: "In einer Kiste liegen 9 rote und 6 blaue Bausteine. Wie viele sind es zusammen?", answer: "15" },
  { id: "M2-032", category: "Mathematik", subcategory: "Sachrechnen", type: "closed", question: "Auf zwei Tellern liegen je 5 Kekse. Wie viele Kekse sind es zusammen?", answer: "10" },
  { id: "M2-033", category: "Mathematik", subcategory: "Sachrechnen", type: "closed", question: "6 Socken werden zu Paaren zusammengelegt. Wie viele Paare sind das?", answer: "3" },
  { id: "M2-034", category: "Mathematik", subcategory: "Sachrechnen", type: "closed", question: "Drei Kinder bekommen je 2 Buntstifte. Wie viele Buntstifte braucht man?", answer: "6" },
  { id: "M2-035", category: "Mathematik", subcategory: "Raum & Form", type: "closed", question: "Welche Form hat drei Ecken?", answer: "Das Dreieck" },
  { id: "M2-036", category: "Mathematik", subcategory: "Raum & Form", type: "closed", question: "Welche Form hat vier gleich lange Seiten und vier Ecken?", answer: "Das Quadrat" },
  { id: "M2-037", category: "Mathematik", subcategory: "Raum & Form", type: "closed", question: "Welche Form hat keine Ecken?", answer: "Der Kreis" },
  { id: "M2-038", category: "Mathematik", subcategory: "Raum & Form", type: "closed", question: "Welcher Körper sieht aus wie ein Ball?", answer: "Die Kugel" },
  { id: "M2-039", category: "Mathematik", subcategory: "Raum & Form", type: "closed", question: "Welcher Körper sieht aus wie ein Spielwürfel?", answer: "Der Würfel" },
  { id: "M2-040", category: "Mathematik", subcategory: "Raum & Form", type: "fun", question: "Wie viele Ecken hat ein viereckiges Dreieck?", answer: "Ein Dreieck kann nicht vier Ecken haben." },
  { id: "M2-041", category: "Mathematik", subcategory: "Raum & Form", type: "closed", question: "Wie viele Ecken hat ein Quadrat?", answer: "4" },
  { id: "M2-042", category: "Mathematik", subcategory: "Raum & Form", type: "closed", question: "Wie viele Ecken hat ein Dreieck?", answer: "3" },
  { id: "M2-043", category: "Mathematik", subcategory: "Muster & Strukturen", type: "closed", question: "Kreis, Quadrat, Kreis, Quadrat, __. Welche Form kommt als Nächstes?", answer: "Kreis" },
  { id: "M2-044", category: "Mathematik", subcategory: "Raumorientierung", type: "closed", question: "Was ist das Gegenteil von links?", answer: "rechts" },
  { id: "M2-045", category: "Mathematik", subcategory: "Größen & Messen", type: "closed", question: "Was ist länger: 1 Meter oder 1 Zentimeter?", answer: "1 Meter" },
  { id: "M2-046", category: "Mathematik", subcategory: "Größen & Messen", type: "closed", question: "Wie viele Cent sind 1 Euro?", answer: "100 Cent" },
  { id: "M2-047", category: "Mathematik", subcategory: "Größen & Messen", type: "closed", question: "50 Cent + 50 Cent sind wie viel?", answer: "1 Euro" },
  { id: "M2-048", category: "Mathematik", subcategory: "Größen & Messen", type: "closed", question: "Wie spät ist es eine Stunde nach 3 Uhr?", answer: "4 Uhr" },
  { id: "M2-049", category: "Mathematik", subcategory: "Größen & Messen", type: "closed", question: "Wie spät ist es eine halbe Stunde nach 9 Uhr?", answer: "9:30 Uhr / halb zehn" },
  { id: "M2-050", category: "Mathematik", subcategory: "Größen & Messen", type: "closed", question: "Wie viele Tage hat eine Woche?", answer: "7" },
  { id: "M2-051", category: "Mathematik", subcategory: "Größen & Messen", type: "closed", question: "Wie viele Monate hat ein Jahr?", answer: "12" },
  { id: "M2-052", category: "Mathematik", subcategory: "Größen & Messen", type: "closed", question: "Wie viele Tage sind zwei Wochen?", answer: "14" },
  { id: "M2-053", category: "Mathematik", subcategory: "Sachrechnen", type: "closed", question: "Ein Stift kostet 3 Euro. Du bezahlst mit 5 Euro. Wie viel bekommst du zurück?", answer: "2 Euro" },
  { id: "M2-054", category: "Mathematik", subcategory: "Sachrechnen", type: "closed", question: "Ein Apfel kostet 2 Euro, eine Banane 1 Euro. Wie viel kostet beides zusammen?", answer: "3 Euro" },
  { id: "M2-055", category: "Mathematik", subcategory: "Daten", type: "closed", question: "5 Kinder wählen Katze, 3 Kinder wählen Hund. Welches Tier hat mehr Stimmen?", answer: "Katze" },
  { id: "M2-056", category: "Mathematik", subcategory: "Daten", type: "closed", question: "4 Kinder wählen Rot und 4 Kinder Blau. Welche Farbe hat mehr Stimmen?", answer: "keine / gleich viele" },
  { id: "M2-057", category: "Mathematik", subcategory: "Wahrscheinlichkeit", type: "closed", question: "In einem Beutel sind nur rote Steine. Welche Farbe ziehst du sicher?", answer: "rot" },
  { id: "M2-058", category: "Mathematik", subcategory: "Wahrscheinlichkeit", type: "closed", question: "Wie viele mögliche Ergebnisse hat ein normaler Münzwurf?", answer: "2 (Kopf oder Zahl)" },
  { id: "M2-059", category: "Mathematik", subcategory: "Zahlbeziehungen", type: "closed", question: "Welche Zahl liegt näher an 20: 16 oder 12?", answer: "16" },
  { id: "M2-060", category: "Mathematik", subcategory: "Muster & Strukturen", type: "closed", question: "Wie geht die Reihe weiter: 1, 3, 5, 7, __?", answer: "9" },

  /* -------------------------------------------------------------- */
  /* DEUTSCH – 60 Fragen                                            */
  /* -------------------------------------------------------------- */
  { id: "D2-001", category: "Deutsch", subcategory: "Laute, Buchstaben & Silben", type: "closed", question: "Mit welchem Buchstaben beginnt das Wort Apfel?", answer: "A" },
  { id: "D2-002", category: "Deutsch", subcategory: "Laute, Buchstaben & Silben", type: "closed", question: "Mit welchem Buchstaben endet das Wort Hund?", answer: "d / D" },
  { id: "D2-003", category: "Deutsch", subcategory: "Laute, Buchstaben & Silben", type: "closed", question: "Mit welchem Buchstaben beginnt das Wort Maus?", answer: "M" },
  { id: "D2-004", category: "Deutsch", subcategory: "Alphabet", type: "closed", question: "Welcher Buchstabe kommt im Alphabet direkt nach A?", answer: "B" },
  { id: "D2-005", category: "Deutsch", subcategory: "Alphabet", type: "closed", question: "Welcher Buchstabe kommt im Alphabet direkt vor D?", answer: "C" },
  { id: "D2-006", category: "Deutsch", subcategory: "Silben", type: "closed", question: "Wie viele Silben hat das Wort Mama?", answer: "2" },
  { id: "D2-007", category: "Deutsch", subcategory: "Silben", type: "closed", question: "Wie viele Silben hat das Wort Banane?", answer: "3" },
  { id: "D2-008", category: "Deutsch", subcategory: "Silben", type: "closed", question: "Wie viele Silben hat das Wort Schule?", answer: "2" },
  { id: "D2-009", category: "Deutsch", subcategory: "Reime", type: "closed", question: "Welches Wort reimt sich auf Haus: Maus oder Hund?", answer: "Maus" },
  { id: "D2-010", category: "Deutsch", subcategory: "Reime", type: "closed", question: "Welches Wort reimt sich auf Sonne: Tonne oder Tisch?", answer: "Tonne" },
  { id: "D2-011", category: "Deutsch", subcategory: "Reime", type: "closed", question: "Welches Wort reimt sich auf Hase: Nase oder Baum?", answer: "Nase" },
  { id: "D2-012", category: "Deutsch", subcategory: "Reime", type: "closed", question: "Welches Wort reimt sich auf Ball: Fall oder Fisch?", answer: "Fall" },
  { id: "D2-013", category: "Deutsch", subcategory: "Wörter", type: "closed", question: "Wie lautet die Mehrzahl von Hund?", answer: "Hunde" },
  { id: "D2-014", category: "Deutsch", subcategory: "Wörter", type: "closed", question: "Wie lautet die Mehrzahl von Katze?", answer: "Katzen" },
  { id: "D2-015", category: "Deutsch", subcategory: "Wörter", type: "closed", question: "Wie lautet die Einzahl von Mäuse?", answer: "Maus" },
  { id: "D2-016", category: "Deutsch", subcategory: "Artikel", type: "closed", question: "Welcher Artikel passt: __ Hund?", answer: "der" },
  { id: "D2-017", category: "Deutsch", subcategory: "Artikel", type: "closed", question: "Welcher Artikel passt: __ Blume?", answer: "die" },
  { id: "D2-018", category: "Deutsch", subcategory: "Artikel", type: "closed", question: "Welcher Artikel passt: __ Kind?", answer: "das" },
  { id: "D2-019", category: "Deutsch", subcategory: "Rechtschreibung", type: "closed", question: "Welche Schreibweise ist richtig: Haus oder haus?", answer: "Haus" },
  { id: "D2-020", category: "Deutsch", subcategory: "Wörter", type: "closed", question: "Welches Wort nennt man ein Nomen (Hauptwort): Hund oder laufen?", answer: "Hund" },
  { id: "D2-021", category: "Deutsch", subcategory: "Wörter", type: "closed", question: "Welches Wort nennt man ein Verb: springen oder rot?", answer: "springen" },
  { id: "D2-022", category: "Deutsch", subcategory: "Wörter", type: "closed", question: "Welches Wort nennt man ein Adjektiv: klein oder Tisch?", answer: "klein" },
  { id: "D2-023", category: "Deutsch", subcategory: "Sätze", type: "closed", question: "Welches Wort ist ein Verb: Der Hund bellt.", answer: "bellt" },
  { id: "D2-024", category: "Deutsch", subcategory: "Sätze", type: "closed", question: "Welches Wort ist ein Nomen: Die Katze schläft.", answer: "Katze" },
  { id: "D2-025", category: "Deutsch", subcategory: "Artikel", type: "closed", question: "Welcher Artikel passt: __ Auto?", answer: "das" },
  { id: "D2-026", category: "Deutsch", subcategory: "Artikel", type: "closed", question: "Welcher Artikel passt: __ Sonne?", answer: "die" },
  { id: "D2-027", category: "Deutsch", subcategory: "Artikel", type: "closed", question: "Welcher Artikel passt: __ Baum?", answer: "der" },
  { id: "D2-028", category: "Deutsch", subcategory: "Satzzeichen", type: "closed", question: "Welches Satzzeichen fehlt: Wie heißt du__", answer: "?" },
  { id: "D2-029", category: "Deutsch", subcategory: "Satzzeichen", type: "closed", question: "Welches Satzzeichen fehlt: Ich spiele__", answer: "." },
  { id: "D2-030", category: "Deutsch", subcategory: "Satzzeichen", type: "closed", question: "Welches Satzzeichen passt zu dem Ausruf: Stopp__", answer: "!" },
  { id: "D2-031", category: "Deutsch", subcategory: "Sätze", type: "open", question: "Ordne zu einem Satz: Mia / ein / isst / Brötchen.", answer: "z. B. Mia isst ein Brötchen. – andere grammatisch richtige Sätze möglich" },
  { id: "D2-032", category: "Deutsch", subcategory: "Sätze", type: "open", question: "Ordne zu einem Satz: noch / schläft / Michael / nicht.", answer: "z. B. Michael schläft noch nicht. – andere grammatisch richtige Sätze möglich" },
  { id: "D2-033", category: "Deutsch", subcategory: "Sätze", type: "closed", question: "Wie viele Wörter hat der Satz: Der Hund rennt.", answer: "3" },
  { id: "D2-034", category: "Deutsch", subcategory: "Sätze", type: "closed", question: "Wie viele Wörter hat der Satz: Ich mag kein warmes Eis.", answer: "5" },
  { id: "D2-035", category: "Deutsch", subcategory: "Buchstaben", type: "closed", question: "Wie viele Buchstaben hat das Wort Haus?", answer: "4" },
  { id: "D2-036", category: "Deutsch", subcategory: "Buchstaben", type: "closed", question: "Wie viele Buchstaben hat das Wort Sonne?", answer: "5" },
  { id: "D2-037", category: "Deutsch", subcategory: "Wörter", type: "closed", question: "Welches Wort ist länger: Haus oder Hausaufgabe?", answer: "Hausaufgabe" },
  { id: "D2-038", category: "Deutsch", subcategory: "Wortbildung", type: "closed", question: "Welches Wort entsteht aus Haus + Tür?", answer: "Haustür" },
  { id: "D2-039", category: "Deutsch", subcategory: "Wortschatz", type: "closed", question: "Was ist das Gegenteil von groß?", answer: "klein" },
  { id: "D2-040", category: "Deutsch", subcategory: "Wortschatz", type: "closed", question: "Was ist das Gegenteil von hell?", answer: "dunkel" },
  { id: "D2-041", category: "Deutsch", subcategory: "Wortschatz", type: "closed", question: "Was ist das Gegenteil von schnell?", answer: "langsam" },
  { id: "D2-042", category: "Deutsch", subcategory: "Laute & Buchstaben", type: "closed", question: "Welches Wort beginnt wie Maus: Mond oder Hund?", answer: "Mond" },
  { id: "D2-043", category: "Deutsch", subcategory: "Laute & Buchstaben", type: "closed", question: "Welches Wort beginnt mit Sch: Schule oder Blume?", answer: "Schule" },
  { id: "D2-044", category: "Deutsch", subcategory: "Rechtschreibung", type: "closed", question: "Welches Wort enthält ie: Tier oder Tür?", answer: "Tier" },
  { id: "D2-045", category: "Deutsch", subcategory: "Rechtschreibung", type: "closed", question: "Welches Wort enthält ei: Bein oder Bin?", answer: "Bein" },
  { id: "D2-046", category: "Deutsch", subcategory: "Rechtschreibung", type: "closed", question: "Welches Wort enthält au: Baum oder Bein?", answer: "Baum" },
  { id: "D2-047", category: "Deutsch", subcategory: "Rechtschreibung", type: "closed", question: "Welches Wort beginnt mit Sp: Spiel oder Ziel?", answer: "Spiel" },
  { id: "D2-048", category: "Deutsch", subcategory: "Rechtschreibung", type: "closed", question: "Welches Wort beginnt mit St: Stein oder Bein?", answer: "Stein" },
  { id: "D2-049", category: "Deutsch", subcategory: "Alphabet", type: "closed", question: "Welches Wort steht alphabetisch zuerst: Apfel oder Ball?", answer: "Apfel" },
  { id: "D2-050", category: "Deutsch", subcategory: "Alphabet", type: "closed", question: "Welches Wort steht alphabetisch zuerst: Maus oder Auto?", answer: "Auto" },
  { id: "D2-051", category: "Deutsch", subcategory: "Lesen", type: "closed", question: "Tom hat einen roten Ball. Welche Farbe hat Toms Ball?", answer: "rot" },
  { id: "D2-052", category: "Deutsch", subcategory: "Lesen", type: "closed", question: "Mia fährt mit dem Bus zur Schule. Womit fährt Mia?", answer: "Mit dem Bus" },
  { id: "D2-053", category: "Deutsch", subcategory: "Lesen", type: "closed", question: "Der Hund schläft im Korb. Wo schläft der Hund?", answer: "im Korb" },
  { id: "D2-054", category: "Deutsch", subcategory: "Lesen", type: "closed", question: "Lina trinkt morgens Wasser. Was trinkt Lina?", answer: "Wasser" },
  { id: "D2-055", category: "Deutsch", subcategory: "Lesen", type: "closed", question: "Welches Wort passt nicht dazu: essen, Tisch, trinken?", answer: "Tisch" },
  { id: "D2-056", category: "Deutsch", subcategory: "Wortschatz", type: "closed", question: "Welches Wort passt nicht dazu: süß, Hund, Katze?", answer: "süß" },
  { id: "D2-057", category: "Deutsch", subcategory: "Wortschatz", type: "closed", question: "Welches Wort passt nicht dazu: lecker, toll, Party?", answer: "Party" },
  { id: "D2-058", category: "Deutsch", subcategory: "Sätze", type: "open", question: "Welches Wort passt: Der Hund __ schnell.", answer: "z. B. rennt, läuft, frisst, spielt – mehrere Lösungen möglich" },
  { id: "D2-059", category: "Deutsch", subcategory: "Silben", type: "closed", question: "Trenne Schule in Silben.", answer: "Schu-le" },
  { id: "D2-060", category: "Deutsch", subcategory: "Silben", type: "closed", question: "Trenne Banane in Silben.", answer: "Ba-na-ne" },

  /* -------------------------------------------------------------- */
  /* ALLGEMEINWISSEN – 60 Fragen (12 je Unterkategorie)             */
  /* -------------------------------------------------------------- */
  { id: "AW2-001", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "In welchem Land liegt Nordrhein-Westfalen?", answer: "Deutschland" },
  { id: "AW2-002", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Was ist die Sonne: ein Stern, ein Planet oder eine Galaxie?", answer: "Ein Stern" },
  { id: "AW2-003", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Welche Notrufnummer gilt in Deutschland für Feuerwehr und Rettungsdienst?", answer: "112" },
  { id: "AW2-004", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Wofür steht die Abkürzung KI?", answer: "Künstliche Intelligenz" },
  { id: "AW2-005", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Mit welchem Land wird die moderne Pizza besonders verbunden?", answer: "Italien" },
  { id: "AW2-006", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Auf welchem Kontinent liegt Deutschland?", answer: "Europa" },
  { id: "AW2-007", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Wie viele Beine hat ein Insekt?", answer: "6" },
  { id: "AW2-008", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Was bedeutet eine rote Ampel im Straßenverkehr?", answer: "Stopp / stehen bleiben" },
  { id: "AW2-009", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Wie heißt das Gerät mit Tasten, mit dem man am Computer Buchstaben eingibt?", answer: "Die Tastatur" },
  { id: "AW2-010", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Mit welchem Land wird Sushi besonders verbunden?", answer: "Japan" },
  { id: "AW2-011", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Welche Sprache sprechen die meisten Menschen in Mexiko?", answer: "Spanisch" },
  { id: "AW2-012", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Wie viele Beine hat eine Spinne?", answer: "8" },
  { id: "AW2-013", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Wer bringt Briefe und Pakete zu den Menschen?", answer: "Postbote/Postbotin / Zusteller/in" },
  { id: "AW2-014", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Wie nennt man ein geheimes Wort zum Anmelden bei einem Konto?", answer: "Das Passwort" },
  { id: "AW2-015", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Welches Instrument hat schwarze und weiße Tasten?", answer: "Das Klavier" },
  { id: "AW2-016", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Wie heißt die Hauptstadt von Frankreich?", answer: "Paris" },
  { id: "AW2-017", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Was stellen Bienen aus Nektar her?", answer: "Honig" },
  { id: "AW2-018", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Wie viele Tage hat ein gewöhnliches Jahr?", answer: "365" },
  { id: "AW2-019", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Womit misst man die Temperatur, z. B. bei Fieber?", answer: "Das Thermometer" },
  { id: "AW2-020", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Wie viele Zwerge kommen im Märchen Schneewittchen vor?", answer: "7" },
  { id: "AW2-021", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Wie heißt die Linie, die zwei Länder trennt?", answer: "Die Grenze" },
  { id: "AW2-022", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Zu welchem Tier entwickelt sich eine Kaulquappe?", answer: "Der Frosch" },
  { id: "AW2-023", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Wie heißt der schwarz-weiß gestreifte Fußgängerübergang auf der Straße?", answer: "Der Zebrastreifen" },
  { id: "AW2-024", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Wie heißen Autos, die ohne Benzin, Diesel oder Gas fahren?", answer: "Elektro-Autos" },
  { id: "AW2-025", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Welches Fest feiern viele Menschen in Deutschland am 24. und 25. Dezember?", answer: "Weihnachten" },
  { id: "AW2-026", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Wie heißt der Ort in der Wüste, wo es Pflanzen und Wasser gibt?", answer: "Die Oase" },
  { id: "AW2-027", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Welcher Teil einer Pflanze nimmt Wasser aus dem Boden auf?", answer: "Die Wurzel / Wurzeln" },
  { id: "AW2-028", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Wie viele Stunden hat ein Tag?", answer: "24" },
  { id: "AW2-029", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Wo kann man Tag und Nacht Informationen, Videos oder Musik finden?", answer: "Das Internet" },
  { id: "AW2-030", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Welche Farbe entsteht beim Mischen von Rot und Gelb?", answer: "Orange" },
  { id: "AW2-031", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Wie nennt man alles, was es im Weltraum gibt – Sterne, Planeten, Galaxien und noch viel mehr?", answer: "Das Universum" },
  { id: "AW2-032", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Welches Tier hält typischerweise Winterschlaf: Igel oder Reh?", answer: "Der Igel" },
  { id: "AW2-033", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Welche Organisation hilft, wenn es brennt?", answer: "Die Feuerwehr" },
  { id: "AW2-034", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Wie heißt ein Computerprogramm auf dem Handy oder Tablet, zum Beispiel WhatsApp, Spotify oder Fotos?", answer: "Eine App" },
  { id: "AW2-035", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Wie heißt der Ort, wo man berühmte Bilder oder Skulpturen sehen kann?", answer: "Das Museum" },
  { id: "AW2-036", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Auf welchem Kontinent liegt Brasilien?", answer: "Südamerika" },
  { id: "AW2-037", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Welches ist das größte Tier der Welt?", answer: "Der Blauwal" },
  { id: "AW2-038", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Wie heißt die Währung, mit der wir in Deutschland bezahlen?", answer: "Der Euro" },
  { id: "AW2-039", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Wozu dient das Notsignal SOS?", answer: "Um in einer Notlage Hilfe zu rufen" },
  { id: "AW2-040", category: "Allgemeinwissen", subcategory: "Kultur", type: "open", question: "Welches Musikinstrument wird mit einem Bogen gespielt und unter das Kinn gehalten?", answer: "Die Violine / Geige; auch die Bratsche ist möglich" },
  { id: "AW2-041", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "In welcher Polarregion leben Eisbären: in der Arktis oder in der Antarktis?", answer: "In der Arktis" },
  { id: "AW2-042", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Was bedeckt den Körper eines Vogels?", answer: "Die Federn" },
  { id: "AW2-043", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Woraus bestehen normale Eiswürfel?", answer: "Aus Wasser" },
  { id: "AW2-044", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Wie heißt ein Buch, das man hören kann?", answer: "Das Hörbuch" },
  { id: "AW2-045", category: "Allgemeinwissen", subcategory: "Kultur", type: "fun", question: "Welches ist das leckerste Gemüse der Welt?", answer: "Das ist Geschmackssache – es gibt keine richtige Antwort." },
  { id: "AW2-046", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Wie heißt die Hauptstadt von Deutschland?", answer: "Berlin" },
  { id: "AW2-047", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Womit atmen Fische im Wasser?", answer: "Die Kiemen" },
  { id: "AW2-048", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Wie heißt ein Ort, an dem man Bücher ausleihen kann?", answer: "Die Bibliothek / Die Bücherei" },
  { id: "AW2-049", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Solltest du deine Handynummer fremden Menschen im Internet geben?", answer: "Nein" },
  { id: "AW2-050", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Wie nennt man eine Geschichte mit Zauberei, sprechenden Tieren oder 'Es war einmal'?", answer: "Das Märchen" },
  { id: "AW2-051", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Welcher Kontinent ist flächenmäßig der größte?", answer: "Asien" },
  { id: "AW2-052", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Bei wie viel Grad Celsius gefriert reines Wasser ungefähr?", answer: "0 °C" },
  { id: "AW2-053", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Wo bekommt man Medikamente?", answer: "In der Apotheke" },
  { id: "AW2-054", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Womit kann man superwinzige Dinge sehen?", answer: "Das Mikroskop" },
  { id: "AW2-055", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Wie nennt man die Person, die in einem Theaterstück oder Film eine Rolle spielt?", answer: "Schauspieler/in" },
  { id: "AW2-056", category: "Allgemeinwissen", subcategory: "Welt & Länder", type: "closed", question: "Welches ist das größte Land der Welt?", answer: "Russland" },
  { id: "AW2-057", category: "Allgemeinwissen", subcategory: "Natur & Tiere", type: "closed", question: "Welche fünf klassischen Sinne haben Menschen?", answer: "sehen, hören, riechen, schmecken, tasten / fühlen" },
  { id: "AW2-058", category: "Allgemeinwissen", subcategory: "Alltag & Gesellschaft", type: "closed", question: "Welche Telefonnummer wählt man in Deutschland für die Polizei?", answer: "110" },
  { id: "AW2-059", category: "Allgemeinwissen", subcategory: "Technik & Medien", type: "closed", question: "Womit kann man Dinge sehen, die weit entfernt sind?", answer: "Das Teleskop" },
  { id: "AW2-060", category: "Allgemeinwissen", subcategory: "Kultur", type: "closed", question: "Aus welcher Bohne wird Schokolade hergestellt?", answer: "Die Kakaobohne" }
];

/* Für die Nutzung in app.js (klassisches Skript, kein Modulsystem) */
if (typeof window !== "undefined") {
  window.QUESTIONS = QUESTIONS;
}
